# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Average At Best
description: "Swapnull's site"
keywords: "Jekyll, blog, site, cs, se, computer, science, software, engineering, node"
url: http://swapnull.co.uk
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "swapnull"
disqus_site_shortname: "swapnull"

# Author settings
author:
  thumb     : images/author.jpg
  email     : martyn.e.rushton@gmail.com
  url       : http://swapnull.co.uk
  github    : http://github.com/swapnull
  twitter   : http://twitter.com/swapnull
  facebook  : http://facebook.com/martyn.rushton.54
  linkedin  : http://linkedin.com/in/martynrushton

# navbar pages
navbar:
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: 
    title: About
  - slug: blog
    title: Blog
  - slug: projects
    title: Projects

projects:
  - title: 3elmdesign.co.uk
    url  : 3elmdesign.co.uk
    tagline: "A bespoke furniture website"
    description: "This site was built using ProcessWire CMS and UiKit front-end framework. I undertook this as subcontracted work from
      @steelstudiosuk where they provided the design and hosting solution."
    image: ../images/projects/3elm.png

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
